tasks:
  - init: ./mvnw install -DskipTests=false
vscode:
  extensions:
      - vscjava.vscode-java-pack
      - redhat.java
      - vscjava.vscode-java-debug
      - vscjava.vscode-java-test
      - vscjava.vscode-maven
