name: CD Java

on: push
branch:
  - dockerfile

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 1.13
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Docker creation
        run: docker build --tag springdemo
  